# Generated by Django 3.1.4 on 2020-12-31 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('access_facta', models.BooleanField(verbose_name='Facta')),
                ('access_geoserver', models.BooleanField(verbose_name='GeoServer')),
                ('access_kaavapino', models.BooleanField(verbose_name='Kaavapino')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wasted_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'authtoken_token',
            },
        ),
    ]
