# Generated by Django 3.1.4 on 2021-01-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtAuthCred',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('system', models.CharField(max_length=20, verbose_name='System')),
                ('cred_owner', models.CharField(max_length=20, verbose_name='CredOwner')),
                ('username', models.CharField(max_length=40, verbose_name='Username')),
                ('credential', models.CharField(max_length=80, verbose_name='Credential')),
            ],
            options={
                'verbose_name': 'ExtAuthCred',
                'verbose_name_plural': 'ExtAuthCreds',
                'db_table': 'ext_auth_cred',
            },
        ),
        migrations.AlterField(
            model_name='token',
            name='access_facta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_facta_creds', to='common_auth.extauthcred', verbose_name='Facta'),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_geoserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_geoserver_creds', to='common_auth.extauthcred', verbose_name='GeoServer'),
        ),
    ]
