# Generated by Django 3.1.4 on 2021-01-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0002_auto_20210104_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='extauthcred',
            name='host_spec',
            field=models.CharField(blank=True, max_length=250, verbose_name='HostSpec'),
        ),
    ]
