openapi: 3.0.3
info:
  title: Helsingin Kaupunki - Kaavapino - GeoServer API
  version: 1.0.0
  description: GeoServer API
paths:
  /api/kaavapino/heartbeat:
    get:
      operationId: kaavapino_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
