openapi: 3.0.3
info:
  title: Helsingin Kaupunki - Kaavapino - GeoServer API
  version: 1.0.0
  description: GeoServer API
paths:
  /api/kaavapino/heartbeat:
    get:
      operationId: kaavapino_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/kaavapino/v1/asemakaava_voimassa/{id}:
    get:
      operationId: kaavapino_v1_asemakaava_voimassa_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/v1/kiinteistotunnus/{id}:
    get:
      operationId: kaavapino_v1_kiinteistotunnus_retrieve
      description: Hae kiinteistö kiinteistötunnuksella
      parameters:
      - in: query
        name: alue
        schema:
          type: string
        description: Filter by alue
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
    post:
      operationId: kaavapino_v1_kiinteistotunnus_create
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/v1/maarekisterikiinteisto/{id}:
    get:
      operationId: kaavapino_v1_maarekisterikiinteisto_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/v1/rakennuskieltoalue_asemakaava/{id}:
    get:
      operationId: kaavapino_v1_rakennuskieltoalue_asemakaava_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/v1/rakennuskieltoalue_yleiskaava/{id}:
    get:
      operationId: kaavapino_v1_rakennuskieltoalue_yleiskaava_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/v1/tontti/{id}:
    get:
      operationId: kaavapino_v1_tontti_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - kaavapino
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /schema/v1/:
    get:
      operationId: schema_v1_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
