openapi: 3.0.3
info:
  title: Helsingin Kaupunki - Kaavapino - API
  version: 1.0.0
  description: Kaavapino API for planning data
paths:
  /api/facta/heartbeat:
    get:
      operationId: facta_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - facta
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/heartbeat:
    get:
      operationId: geoserver_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - geoserver
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/heartbeat:
    get:
      operationId: kaavapino_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - kaavapino
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components: {}
