openapi: 3.0.3
info:
  title: Helsingin Kaupunki - Kaavapino - GeoServer API
  version: 1.0.0
  description: GeoServer API
paths:
  /api/facta/heartbeat:
    get:
      operationId: facta_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - facta
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/heartbeat:
    get:
      operationId: geoserver_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - geoserver
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/asemakaava_voimassa/{id}:
    get:
      operationId: geoserver_v1_asemakaava_voimassa_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/kiinteistotunnus/{id}:
    get:
      operationId: geoserver_v1_kiinteistotunnus_retrieve
      description: Hae kiinteistö kiinteistötunnuksella
      parameters:
      - in: query
        name: alue
        schema:
          type: string
        description: (test-version only) Filter by alue
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KiinteistoV1'
              examples:
                ExampleResponse:
                  value:
                    datanomistaja: Helsinki/Kami
                    id: 156
                    kiinteisto: 91-3-9903-101
                    kiinteistotunnus: 09100399030101
                    kunta: 091
                    luontipvm: '2013-12-09'
                    muokkauspvm: '2014-06-10'
                    paivitetty_tietopalveluun: '2021-01-04'
                    rekisterointipvm: '1980-05-30'
                    ryhma: '9903'
                    sijaintialue: '003'
                    yksikko: '0101'
                    gml_id: Kiinteisto_alue.156.geom.1
                    geom: <gml:Polygon xmlns:gml="http://www.opengis.net/gml/3.2"
                      srsName="urn:ogc:def:crs:EPSG::3879"><gml:exterior><gml:LinearRing><gml:posList>6672759.0098
                      2.54969922149E7 6672701.3892 2.54969952458E7 6672711.2563 2.54971894828E7
                      6672768.3387 2.54971866207E7 6672759.0098 2.54969922149E7</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon>
                  summary: Detailed description of fields returned as response
                  description: "\n            Example 09100399030101 is part of Espa,\
                    \ esplanade and urban park in downtown Helsinki.\n           \
                    \ Group 9903 indicates a public space, a park.\n            \n\
                    \            Fields:\n            * datanomistaja: Owner of this\
                    \ data in City of Helsinki\n            * id: Database unique\
                    \ id\n            * gml_id: Database unique id in GML (ISO 19136:2007)\n\
                    \            * kiinteistotunnus: zero padded 14 digit (3-3-4-4)\
                    \ representation of field 'kiinteisto'\n            * kiinteisto:\
                    \ dash-separated value of kunta-sijaintialue-ryhma-yksikko\n \
                    \           * kunta: Number from list https://tilastokeskus.fi/fi/luokitukset/kunta/\n\
                    \            * sijaintialue: region\n            * ryhma: group\
                    \ in region or if public space, following type codes are used:\n\
                    \              * 9901 Streets\n              * 9902 Marketplaces\
                    \ and squares\n              * 9903 Parks\n              * 9904\
                    \ Sports\n              * 9905 Recreational areas\n          \
                    \    * 9906 Traffic\n              * 9907 Danger\n           \
                    \   * 9908 Special and preserved areas\n              * 9909 Water\n\
                    \            * yksikko: unit in group\n            * luontipvm:\
                    \ Database data creation date\n            * muokkauspvm\": Database\
                    \ data modification date\n            * paivitetty_tietopalveluun\"\
                    : Database read date\n            * \"rekisterointipvm\": Data\
                    \ creation date (earliest 1st Jan 1800)\n            * geom: String,\
                    \ GML representation of the geographical area for this data\n\
                    \            "
          description: ''
        '401':
          content:
            application/json:
              schema:
                type: string
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: string
          description: ''
    post:
      operationId: geoserver_v1_kiinteistotunnus_create
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/maarekisterikiinteisto/{id}:
    get:
      operationId: geoserver_v1_maarekisterikiinteisto_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/neighbourhood/{id}:
    get:
      operationId: geoserver_v1_neighbourhood_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/rakennuskieltoalue_asemakaava/{id}:
    get:
      operationId: geoserver_v1_rakennuskieltoalue_asemakaava_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/rakennuskieltoalue_yleiskaava/{id}:
    get:
      operationId: geoserver_v1_rakennuskieltoalue_yleiskaava_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/geoserver/v1/tontti/{id}:
    get:
      operationId: geoserver_v1_tontti_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Kiinteistötunnus to get data for
        required: true
      tags:
      - geoserver
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/kaavapino/heartbeat:
    get:
      operationId: kaavapino_heartbeat_retrieve
      description: Simple service is alive test
      tags:
      - kaavapino
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /schema/v1/:
    get:
      operationId: schema_v1_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    KiinteistoV1:
      type: object
      properties:
        datanomistaja:
          type: string
          maxLength: 40
        id:
          type: integer
        kiinteisto:
          type: string
          maxLength: 24
        kiinteistotunnus:
          type: string
          maxLength: 20
        kunta:
          type: string
          maxLength: 3
          minLength: 3
        luontipvm:
          type: string
          format: date
        muokkauspvm:
          type: string
          format: date
        paivitetty_tietopalveluun:
          type: string
          format: date
        rekisterointipvm:
          type: string
          format: date
        ryhma:
          type: string
          maxLength: 4
          minLength: 4
        sijaintialue:
          type: string
          maxLength: 3
          minLength: 3
        yksikko:
          type: string
          maxLength: 4
          minLength: 4
        gml_id:
          type: string
          maxLength: 80
        geom:
          type: string
      required:
      - datanomistaja
      - geom
      - id
      - kiinteisto
      - kiinteistotunnus
      - kunta
      - luontipvm
      - muokkauspvm
      - paivitetty_tietopalveluun
      - rekisterointipvm
      - ryhma
      - sijaintialue
      - yksikko
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
