kind: Service
apiVersion: v1
metadata:
  name: kaavoitus-api
spec:
  selector:
    app: kaavoitus-api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: api
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaavoitus-api
  labels:
    app: kaavoitus-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaavoitus-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kaavoitus-api
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      volumes:
        - name: mock-data
          persistentVolumeClaim:
            claimName: mock-data
      containers:
      - name: kaavoitus-api
        image: ${CICD_REGISTRY}/kaavoitus-api:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
        volumeMounts:
        - mountPath: "/kaavoitus-api/mock-data"
          name: mock-data
        ports:
        - containerPort: 8000
        env:
        - name: FACTA_DB_MOCK_DATA_DIR
          value: mock-data/
        - name: ALLOWED_HOSTS
          value: localhost,api
