pipelines:
  default:
    - step:
        name: Build & test
        caches:
          - docker
        services:
          - docker
        script:
          - docker build -f Dockerfile.test . -t kaavoitus-api-test
          - docker run kaavoitus-api-test flake8
          - docker run kaavoitus-api-test black --check .
