version: "3.5"
services:
  kaavoitus-api:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    image: kaavoitus-api
    volumes:
      - .:/kaavoitus-api:rw,cached
      - ./mock-data:/kaavoitus-api/mock-data
      - ./django-db/db.sqlite3:/kaavoitus-api/db/db.sqlite3
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
      - FACTA_DB_MOCK_DATA_DIR=mock-data/
      - USE_JSON_READER=True
    ports:
      - "8000:8000"
    container_name: kaavoitus-api

