version: "3.5"
services:
  kaavoitus-api:
    build:
      context: "."
    image: kaavoitus-api
    volumes:
      - ./mock-data:/kaavoitus-api/mock-data
      - ./django-db/db.sqlite3:/kaavoitus-api/db.sqlite3:rw,consistent
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost
      - FACTA_DB_MOCK_DATA_DIR=mock-data/
    ports:
      - "8000:8000"
    container_name: kaavapino-api

