version: "3.5"
services:
  kaavoitus-api:
    build:
      context: "."
    image: kaavoitus-api
    volumes:
      - ./mock-data:/kaavoitus-api/mock-data
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost
    ports:
      - "8000:8000"
    container_name: kaavapino-api

