from .kiinteistonomistajatv1serializer import KiinteistonOmistajatV1Serializer
from .kiinteistonomistajav1serializer import KiinteistonOmistajaV1Serializer
from .kiinteistonhaltijatv1serializer import KiinteistonHaltijatV1Serializer
from .kiinteistonhaltijav1serializer import KiinteistonHaltijaV1Serializer
from .kiinteistoaddressv1serializer import KiinteistoAddressV1Serializer
from .kiinteistodatav1serializer import KiinteistonDataV1Serializer
from .rakennuksenomistajatv1serializer import RakennuksenOmistajatV1Serializer
from .rakennuksenomistajav1serializer import RakennuksenOmistajaV1Serializer
